name: 'Impekable Twilio Studio Control'
author: 'Impekable'
description: 'Automated access and version control for Twilio Studio'
inputs:
  twilio-master-flow-sid:
    description: 'The sid of the main flow that you want the development flows to be based on'
    required: false
  github-token:
    description: 'Github token to create json files. This does not need to be filled out manually. Github automatically fills in secrets.GITHUB_TOKEN'
    required: true
  TWILIO_ACCOUNT_SID_PRODUCTION:
    description: 'Twilio Account SID for production environment'
    required: true
  TWILIO_API_KEY_PRODUCTION:
    description: 'Twilio API Key for production environment'
    required: true
  TWILIO_API_SECRET_PRODUCTION:
    description: 'Twilio API Secret for production environment'
    required: true
  TWILIO_ACCOUNT_SID_DEVELOPMENT:
    description: 'Twilio Account SID for development environment'
    required: true
  TWILIO_API_KEY_DEVELOPMENT:
    description: 'Twilio API Key for development environment'
    required: true
  TWILIO_API_SECRET_DEVELOPMENT:
    description: 'Twilio API Secret for development environment'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'red'
  icon: 'message-circle'