name: 'Impekable Twilio Studio Control'
author: 'Impekable'
description: 'Automated version control for Twilio Studio Flows'
inputs:
  masterFlow:
    description: 'The main flow'
    required: false
  githubToken:
    description: 'Github token to create json files'
    required: true
  TWILIO_ACCOUNT_SID:
    description: 'A Twilio Account SID. Can alternatively be stored in environment'
    required: true
  TWILIO_API_KEY:
    description: 'A Twilio API Key. Can alternatively be stored in environment'
    required: true
  TWILIO_API_SECRET:
    description: 'A Twilio API Secret. Can alternatively be stored in environment'
    required: true
outputs:
  messageSid:
    description: 'The Twilio Flow SID'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'red'
  icon: 'message-circle'